Autoid collecting
Reaping2/Reaping2 pull request #127
Opened 2016-11-19 14:51 UTC by weanti

Added autoid collecting tool that gathers potential autoids from source files and from content files
Adapted autoid initialization

2016-11-24 21:10 UTC, HalalUr approved these changes
I can't fully review this PR because of the CMakeLists part. We need a CMAKE expert here

2016-11-24 21:10 UTC, HalalUr commented on tools/aicollector/main.cpp
> +    for ( auto it = root.begin(), e = root.end(); it != e; ++it)
for ( auto const& val : root ) or auto& val:root works with json::value too (possibly auto&& is good too).

2016-11-24 21:10 UTC, HalalUr commented on run/CMakeLists.txt
> +                    --ext cpp h
You wrote comma separated. Maybe I just don't know what's happening

2016-11-25 15:46 UTC, MrPepperoni commented on run/CMakeLists.txt
> +        message(STATUS "aicollector found! Autids will be collected.")
O

2016-11-25 18:53 UTC, MrPepperoni requested changes
dependencies need fixing

2016-11-25 18:53 UTC, MrPepperoni commented on run/CMakeLists.txt
> +                    --ext cpp h
the help text is incorrect, the usage is fine

2016-11-25 18:53 UTC, MrPepperoni commented on run/CMakeLists.txt
> +        DEPENDS ${content})
data.pkg depends on autoids, otherwise packaging might happen before generation

2016-11-26 14:16 UTC, weanti commented on run/CMakeLists.txt
> +                    --ext cpp h
The description is wrong, I'll update the help text

2016-11-27 13:25 UTC, weanti commented on run/CMakeLists.txt
> +        message(STATUS "aicollector found! Autids will be collected.")
Maybe a bit more specific? Use Error instead of Status?

2016-11-28 07:40 UTC, MrPepperoni commented on run/CMakeLists.txt
> +        message(STATUS "aicollector found! Autids will be collected.")
Aut_O_ids will be collected.

2016-11-28 07:46 UTC, weanti commented on run/CMakeLists.txt
> +        message(STATUS "aicollector found! Autids will be collected.")
Ah, okay. Thanks

2016-11-28 20:04 UTC, MrPepperoni approved these changes

2016-11-28 20:04 UTC, merged